#!/usr/bin/env bash

IMAGE_OUTPUT_DIR="$HOME/Pictures/Screenshots"
filename="$IMAGE_OUTPUT_DIR/screenshot_$(date +%s).png"
scrot $1 $2 $3 "$filename" && xclip -selection clipboard -t image/png "$filename" 
notify-send -i "$filename" "Screenshot" "Screenshot saved to $filename and copied to clipboard" -r 923
