#!/usr/bin/env bash

status=$(curl -s -o /dev/null -w "%{http_code}" https://aur.archlinux.org/rpc/?v=5)
if [ "$status" = "200" ]; then
    printf "%%{F#9ece6a}󰣇%%{F-} \n"
else
    printf "%%{F#F7768E}󰣇%%{F-} \n"
fi

