#!/bin/bash

# Terminate already running instances
pkill -x bspc

# Set monitor layout
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Set window behavior
bspc config border_width         2
bspc config window_gap           8
bspc config split_ratio          0.5
bspc config focus_follows_pointer true
bspc config automatic_scheme     alternate

# Set window rules
bspc rule -a Gimp state=floating
bspc rule -a LibreWolf desktop=2 follow=on
bspc rule -a Kitty desktop=1 focus=on

# Start polybar (if used)
pgrep -x polybar || polybar &

# Start sxhkd (for keybindings)
pgrep -x sxhkd || sxhkd &

# Set wallpaper (if using feh)
feh --bg-scale ~/Pictures/wallpaper.jpg &

# Enable compositor (if using picom)
pgrep -x picom || picom --experimental-backends &

# Start notification daemon
pgrep -x dunst || dunst &
